version: '3.9'

services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000 # Corrected port number
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1 # Corrected syntax
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1 # Corrected syntax
      - CELERY_BROKER=redis://redis:6379/0 # Use 'redis' as the hostname
      - CELERY_BACKEND=redis://redis:6379/0 # Use 'redis' as the hostname
    depends_on:
      - pgdb
      - redis
  celery:
    build: .
    command: celery --app=core worker --loglevel=INFO # Updated command
    volumes:
      - .:/usr/src/app/
    depends_on:
      - django
      - redis
  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
  redis:
    image: "redis:alpine"
volumes:
  pgdata:
